### ISSUE TITLE
'break' not in the 'loop' or 'switch' context

### ISSUE THREAD

**Issue by joggeli** [kartik-v/yii2-mpdf#30]
PHP Version 7.0.4

There is an error in **\vendor\kartik-v\mpdf\classes\svg.php** on line 2710 when generating a PDF with SVG files in it.

> 'break' not in the 'loop' or 'switch' context.

Replacing the "break" with "return" seems to work as a temporary fix.

**Comment by joggeli** [comment]
It looks like this plugin uses an outdated version of mpdf which is not compatible with PHP 7.

**Comment by fmp-martins** [comment]
I have the same issue, but if I try the workaround of replacing the "break" with "return", my PDF gets a lot of garbage in the end.

This component needs to be updated because I'm also getting some Acrobat Reader (on latest version) warning about loading fonts and it no longer shows latin chars. It works fine with other readers though.

**Comment by kartik-v** [comment]
This extension has been changed some time back to use mpdf1/mpdf repo...
